/**
 * SAHAYAK AI - DIET (District Institute of Education) Dashboard
 * Features: District heatmaps, FLN gaps, training needs, exportable summaries
 */

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
    MapPin,
    TrendingUp,
    AlertTriangle,
    FileDown,
    BarChart3,
    BookOpen,
    Users,
    Target,
    PieChart
} from 'lucide-react';
import { dashboardAPI } from '../api/client';

export default function DIETDashboard({ user }) {
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState(null);
    const [timeRange, setTimeRange] = useState(30);

    useEffect(() => {
        loadDashboard();
    }, [timeRange]);

    async function loadDashboard() {
        try {
            setLoading(true);
            const response = await dashboardAPI.getDIET(timeRange);
            if (response?.data) {
                setData(response.data);
            }
        } catch (error) {
            console.error('Error loading DIET dashboard:', error);
        } finally {
            setLoading(false);
        }
    }

    function exportSummary() {
        if (!data?.exportable_summary) return;

        const summary = data.exportable_summary;
        const text = `
SAHAYAK AI - District Summary Report
Generated: ${summary.generated_at}
=====================================

OVERVIEW
--------
Total Teachers: ${summary.total_teachers}
Total SOS Requests: ${summary.total_sos_requests}
Blocks Analyzed: ${summary.blocks_analyzed}

TOP TRAINING PRIORITIES
-----------------------
${summary.top_training_needs?.map((t, i) => `${i + 1}. ${t.area} (${t.incident_count} incidents) - Priority: ${t.priority}`).join('\n') || 'No priorities identified'}

KEY INSIGHTS
------------
${summary.key_insights?.map((insight, i) => `• ${insight}`).join('\n') || 'No insights available'}

=====================================
Report generated by SAHAYAK AI
    `.trim();

        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `sahayak_district_report_${new Date().toISOString().split('T')[0]}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    }

    if (loading) {
        return (
            <div className="flex items-center justify-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-4 border-rose-500 border-t-transparent" />
            </div>
        );
    }

    const summary = data?.summary || {
        total_teachers: 0,
        total_blocks: 0,
        total_sos: 0,
        avg_sos_per_teacher: 0
    };

    const flnGaps = data?.fln_gaps || {};

    return (
        <div className="p-6 space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
                        <Target className="text-rose-500" />
                        District Dashboard
                    </h1>
                    <p className="text-gray-600 mt-1">
                        District-wide analytics and training need assessment
                    </p>
                </div>
                <div className="flex items-center gap-3">
                    <select
                        value={timeRange}
                        onChange={(e) => setTimeRange(parseInt(e.target.value))}
                        className="px-4 py-2 border rounded-lg bg-white text-gray-700 focus:ring-2 focus:ring-rose-500"
                    >
                        <option value={7}>Last 7 days</option>
                        <option value={14}>Last 14 days</option>
                        <option value={30}>Last 30 days</option>
                    </select>
                    <button
                        onClick={exportSummary}
                        className="px-4 py-2 bg-rose-500 hover:bg-rose-600 text-white rounded-lg flex items-center gap-2 transition-colors"
                    >
                        <FileDown size={18} />
                        Export Report
                    </button>
                </div>
            </div>

            {/* Stats Overview */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <StatCard
                    icon={<Users className="text-blue-500" />}
                    label="Total Teachers"
                    value={summary.total_teachers}
                    bg="bg-blue-50"
                />
                <StatCard
                    icon={<MapPin className="text-green-500" />}
                    label="Blocks"
                    value={summary.total_blocks}
                    bg="bg-green-50"
                />
                <StatCard
                    icon={<AlertTriangle className="text-orange-500" />}
                    label="Total SOS"
                    value={summary.total_sos}
                    bg="bg-orange-50"
                />
                <StatCard
                    icon={<TrendingUp className="text-purple-500" />}
                    label="Avg SOS/Teacher"
                    value={summary.avg_sos_per_teacher}
                    bg="bg-purple-50"
                />
            </div>

            {/* Main Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Block Heatmap */}
                <div className="bg-white rounded-xl shadow-sm p-6 lg:col-span-2">
                    <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                        <MapPin size={18} className="text-rose-500" />
                        Block-wise Activity Heatmap
                    </h3>
                    <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                        {data?.block_heatmap?.length > 0 ? (
                            data.block_heatmap.map((block, i) => {
                                const intensity = Math.min(1, block.intensity / 10);
                                return (
                                    <motion.div
                                        key={block.block || i}
                                        initial={{ opacity: 0, scale: 0.9 }}
                                        animate={{ opacity: 1, scale: 1 }}
                                        transition={{ delay: i * 0.05 }}
                                        className="p-4 rounded-lg relative overflow-hidden"
                                        style={{
                                            backgroundColor: `rgba(225, 29, 72, ${0.1 + intensity * 0.5})`
                                        }}
                                    >
                                        <h4 className="font-semibold text-gray-900">{block.block}</h4>
                                        <div className="flex justify-between text-sm mt-2">
                                            <span className="text-gray-600">
                                                👩‍🏫 {block.teachers}
                                            </span>
                                            <span className="text-gray-600">
                                                🆘 {block.sos_count}
                                            </span>
                                        </div>
                                    </motion.div>
                                );
                            })
                        ) : (
                            <p className="text-gray-500 col-span-full text-center py-8">
                                No block data available
                            </p>
                        )}
                    </div>
                </div>

                {/* FLN Gaps */}
                <div className="bg-white rounded-xl shadow-sm p-6">
                    <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                        <BookOpen size={18} className="text-amber-500" />
                        FLN Concept Gaps
                    </h3>
                    <div className="space-y-4">
                        {Object.entries(flnGaps).map(([area, count]) => {
                            const total = Object.values(flnGaps).reduce((a, b) => a + b, 0);
                            const percent = total > 0 ? Math.round((count / total) * 100) : 0;

                            return (
                                <div key={area}>
                                    <div className="flex justify-between text-sm mb-1">
                                        <span className="text-gray-700 capitalize">
                                            {area.replace(/_/g, ' ')}
                                        </span>
                                        <span className="text-gray-500">{count} issues</span>
                                    </div>
                                    <div className="h-3 bg-gray-100 rounded-full overflow-hidden">
                                        <motion.div
                                            initial={{ width: 0 }}
                                            animate={{ width: `${percent}%` }}
                                            transition={{ duration: 0.5 }}
                                            className="h-full bg-gradient-to-r from-amber-400 to-orange-500 rounded-full"
                                        />
                                    </div>
                                </div>
                            );
                        })}
                        {Object.keys(flnGaps).length === 0 && (
                            <p className="text-gray-500 text-center py-4">No FLN data yet</p>
                        )}
                    </div>
                </div>

                {/* Training Needs */}
                <div className="bg-white rounded-xl shadow-sm p-6">
                    <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                        <Target size={18} className="text-red-500" />
                        Training Needs
                    </h3>
                    <div className="space-y-3">
                        {data?.training_needs?.length > 0 ? (
                            data.training_needs.map((need, i) => (
                                <motion.div
                                    key={i}
                                    initial={{ opacity: 0, x: -20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: i * 0.1 }}
                                    className={`p-3 rounded-lg border ${need.priority === 'high'
                                            ? 'bg-red-50 border-red-200'
                                            : 'bg-yellow-50 border-yellow-200'
                                        }`}
                                >
                                    <div className="flex items-center justify-between">
                                        <span className="font-medium text-gray-900">{need.area}</span>
                                        <span className={`text-xs px-2 py-1 rounded-full font-medium ${need.priority === 'high'
                                                ? 'bg-red-100 text-red-700'
                                                : 'bg-yellow-100 text-yellow-700'
                                            }`}>
                                            {need.priority}
                                        </span>
                                    </div>
                                    <p className="text-sm text-gray-600 mt-1">
                                        {need.incident_count} incidents reported
                                    </p>
                                </motion.div>
                            ))
                        ) : (
                            <p className="text-gray-500 text-center py-4">
                                No training needs identified yet
                            </p>
                        )}
                    </div>
                </div>

                {/* Subject Distribution */}
                <div className="bg-white rounded-xl shadow-sm p-6">
                    <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                        <PieChart size={18} className="text-indigo-500" />
                        Subject Distribution
                    </h3>
                    <div className="space-y-3">
                        {Object.entries(data?.subject_distribution || {}).map(([subject, count]) => (
                            <div key={subject} className="flex items-center justify-between">
                                <span className="text-gray-700">{subject}</span>
                                <div className="flex items-center gap-2">
                                    <div className="w-24 h-2 bg-gray-100 rounded-full overflow-hidden">
                                        <div
                                            className="h-full bg-indigo-500 rounded-full"
                                            style={{ width: `${Math.min(100, count * 5)}%` }}
                                        />
                                    </div>
                                    <span className="text-sm text-gray-500 w-8">{count}</span>
                                </div>
                            </div>
                        ))}
                        {Object.keys(data?.subject_distribution || {}).length === 0 && (
                            <p className="text-gray-500 text-center py-4">No subject data</p>
                        )}
                    </div>
                </div>

                {/* Grade Distribution */}
                <div className="bg-white rounded-xl shadow-sm p-6">
                    <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                        <BarChart3 size={18} className="text-teal-500" />
                        Grade-wise Issues
                    </h3>
                    <div className="flex items-end gap-2 h-40">
                        {Object.entries(data?.grade_distribution || {}).map(([grade, count], i) => (
                            <div key={grade} className="flex-1 flex flex-col items-center">
                                <motion.div
                                    initial={{ height: 0 }}
                                    animate={{ height: `${Math.max(10, count * 10)}%` }}
                                    transition={{ delay: i * 0.1 }}
                                    className="w-full bg-gradient-to-t from-teal-500 to-cyan-400 rounded-t"
                                />
                                <span className="text-xs text-gray-500 mt-2">Cl {grade}</span>
                            </div>
                        ))}
                        {Object.keys(data?.grade_distribution || {}).length === 0 && (
                            <p className="text-gray-500 text-center w-full">No grade data</p>
                        )}
                    </div>
                </div>
            </div>

            {/* Key Insights */}
            {data?.exportable_summary?.key_insights?.length > 0 && (
                <div className="bg-gradient-to-r from-rose-50 to-orange-50 rounded-xl p-6">
                    <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                        💡 Key Insights
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        {data.exportable_summary.key_insights.map((insight, i) => (
                            <div key={i} className="bg-white/50 rounded-lg p-4">
                                <p className="text-gray-700">{insight}</p>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
}

function StatCard({ icon, label, value, bg }) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className={`${bg} rounded-xl p-5`}
        >
            <div className="flex items-center gap-3">
                <div className="p-2.5 bg-white rounded-lg shadow-sm">
                    {icon}
                </div>
                <div>
                    <p className="text-sm text-gray-600">{label}</p>
                    <p className="text-2xl font-bold text-gray-900">{value}</p>
                </div>
            </div>
        </motion.div>
    );
}
